# .travis.yml sets up Travis CI to build & deploy the site.
language: r
python:
  - 3.5
sudo: false
cache:
  packages: true
  directories:
  - _cache
  - $HOME/.cache/pip
  - _virtenv
  pip: true
git:
  depth: 3
before_install:
  - sudo apt-get install -y r-cran-ncdf4 libudunits2-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev python3 python3-pip
  - pip install --user virtualenv
  - virtualenv _virtenv
  - source ./_virtenv/bin/activate
before_script:
  # git setup
  - git config --global user.name "Tylar Murray (Travis-CI)"
  - git config --global user.email "tylarmurray@mail.usf.edu"
  # r python libs
  - Rscript -e 'devtools::install_github("jeremiaheb/rvc")'
  - Rscript -e 'devtools::install_github("timelyportfolio/d3treeR")'
  - Rscript -e 'devtools::install_github("iobis/robis", ref="obis2")'
  # python libs
  - pip install -r requirements.txt
  # matplotlib backend:
  - export MPLBACKEND=agg
script:
  - echo === BUILD ROOT
  - Rscript -e 'rmarkdown::render_site()'
  - echo === BUILD PAGES DIR
  - cp _site.yml pages/_site.yml
  - cd pages
  - Rscript -e 'rmarkdown::render_site()'
  - cd ..
  - echo === BUILD EXAMPLES DIR
  - cp _site.yml examples/_site.yml
  - cd examples
  - Rscript -e 'rmarkdown::render_site()'
  - cd ..
after_success:
  - echo === PUSHING TO GITHUB
  # - git ls-files -m -o -X .gitignore -x '*.html' | xargs ls -lh
  # - git ls-files -m -o -X .gitignore -x '*.html' | xargs git add
  # see #17
  - find . -type f -not -path '*.git*' -a -not -name '*~' -a -not -name '*.html' -print0 | xargs -0 git add
  - git commit -m "travis-ci.org Rmd render [ci skip]"
  - git push --force https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:gh-pages
notifications:
  email:
    recipients:
    - tylarmurray@mail.usf.edu
    on_success: change
    on_failure: change
# NOTE: the following will deploy the rmarkdown site directly (skipping jekyll):
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN
#   keep-history: true
#   on:
#     branch: master
#   target-branch: gh-pages
#   local-dir: _site
